#!/usr/bin/env perl

system "mv param param.orig";
prochyb("up_00",1);
prochyb("dn_00",2);

sub prochyb
{
    my $x = shift;
    my $n = shift;
    my $hybfn = "Gamma_${x}.dat";
    -e $hybfn or die "Hybridisation function $hybfn not found.";
    -e "FSOL_${x}.dat" or die "FSOL_${x}.dat not found.";
    -e "FSOLNEG_${x}.dat" or die "FSOLNEG_{x}.dat not found.";

    system "cp param.orig param";
    system "echo dos=Gamma_${x}.dat >>param";
    system "cp FSOL_${x}.dat FSOL.dat";
    system "cp FSOLNEG_${x}.dat FSOLNEG.dat";
    system "nrgchain";

    -e "xi.dat" && -e "zeta.dat" && -e "theta.dat" or die "Wilson chain coefficients not found.";

    system "mv xi.dat xi${n}.dat";
    system "mv zeta.dat zeta${n}.dat";
    system "mv theta.dat theta${n}.dat";
}
